import type { Room, PaymentMethod } from "./types"

export const rooms: Room[] = [
  {
    id: "1",
    name: "Superior With Window",
    type: "1 giường king",
    beds: "1 giường king",
    amenities: ["Hướng mặt phố", "Còn 2 phòng"],
    area: "17m2",
    guests: 2,
    rooms: 2,
    priceWeekday: 650000,
    priceWeekend: 850000,
    images: ["/placeholder.svg?height=200&width=300"],
  },
  {
    id: "2",
    name: "Studio Double With Pool View",
    type: "1 giường queen",
    beds: "1 giường queen",
    amenities: ["Hướng mặt phố", "Còn 1 phòng"],
    area: "20m2",
    guests: 2,
    rooms: 1,
    priceWeekday: 750000,
    priceWeekend: 950000,
    images: ["/placeholder.svg?height=200&width=300"],
  },
  {
    id: "3",
    name: "Studio Twin With Window",
    type: "2 giường đơn",
    beds: "2 giường đơn",
    amenities: ["Hướng mặt phố", "Còn 1 phòng"],
    area: "20m2",
    guests: 2,
    rooms: 1,
    priceWeekday: 750000,
    priceWeekend: 950000,
    images: ["/placeholder.svg?height=200&width=300"],
  },
  {
    id: "4",
    name: "Deluxe With Balcony",
    type: "1 giường king,",
    beds: "1 giường king,",
    amenities: ["Hướng mặt phố", "Còn 2 phòng"],
    area: "20m2",
    guests: 2,
    rooms: 2,
    priceWeekday: 910000,
    priceWeekend: 1110000,
    images: ["/placeholder.svg?height=200&width=300"],
  },
  {
    id: "5",
    name: "Family Room With Bathtub and Pool Garden View",
    type: "2 giường queen",
    beds: "2 giường queen",
    amenities: ["Hướng mặt phố", "Còn 1 phòng"],
    area: "30m2",
    guests: 4,
    rooms: 1,
    priceWeekday: 1050000,
    priceWeekend: 1250000,
    images: ["/placeholder.svg?height=200&width=300"],
  },
  
{
    id: "6",
    name: "Alex Premium Private Pool",
    type: "2 giường queen",
    beds: "2 giường queen",
    amenities: ["Hướng mặt phố", "Còn 1 phòng"],
    area: "30m2",
    guests: 4,
    rooms: 1,
    priceWeekday: 2210000,
    priceWeekend: 2410000,
    images: ["/placeholder.svg?height=200&width=300"],
  }
]

export const paymentMethods: PaymentMethod[] = [
  { id: "visa_mastercard", name: "Thẻ tín dụng hoặc thẻ ghi nợ", icon: "💳" },
  { id: "momo", name: "Momo", icon: "📱" },
  { id: "zalopay", name: "ZaloPay", icon: "💰" },
  { id: "crypto", name: "Crypto", icon: "₿" },
]
